export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SIGNUP = "SIGNUP";
export const VERIFY_ACCOUNT_RESPONSE = "VERIFY_ACCOUNT_RESPONSE ";
export const FORGET_PASSWORD_RESPOSE = "FORGET_PASSWORD_RESPOSE";
export const RESET_PASSWORD_RESPOSE = "RESET_PASSWORD_RESPOSE";
export const CLEAR_FORGET_PASSWORD_RESPOSE = "CLEAR_FORGET_PASSWORD_RESPOSE";
export const CLEAR_RESET_PASSWORD_RESPOSE = "CLEAR_RESET_PASSWORD_RESPOSE";

// Car Trends
export const SET_SELECTED_CAR = "SET_SELECTED_CAR";

export const CAR_TRENDS = "CAR_TRENDS";

export const CAR_DETAILS = "CAR_DETAILS";

export const CARS_LAST_RECORD = "CARS_LAST_RECORD";
// Dashbord
export const SET_DASHBOARD_SELECTED_CAR = "SET_DASHBOARD_SELECTED_CAR";
export const HOURLY_AVG_RPM = "HOURLY_AVG_RPM";
export const WEEKLY_AVG_RPM = "WEEKLY_AVG_RPM";
export const HOURLY_AVG_SPEED = "HOURLY_AVG_SPEED";
export const WEEKLY_AVG_SPEED = "WEEKLY_AVG_SPEED";
export const HOURLY_AVG_FUEL = "HOURLY_AVG_FUEL";
export const WEEKLY_AVG_FUEL = "WEEKLY_AVG_FUEL";

export const DASHBOARD_HR_SPEED_LOADER_START = "DASHBOARD_HR_SPEED_LOADER_START";
export const DASHBOARD_HR_RPM_LOADER_START = "DASHBOARD_HR_RPM_LOADER_START";
export const DASHBOARD_HR_FUEL_LOADER_START = "DASHBOARD_HR_FUEL_LOADER_START";

export const DASHBOARD_WK_SPEED_LOADER_START = "DASHBOARD_WK_SPEED_LOADER_START";
export const DASHBOARD_WK_RPM_LOADER_START = "DASHBOARD_WK_RPM_LOADER_START";
export const DASHBOARD_WK_FUEL_LOADER_START = "DASHBOARD_WK_FUEL_LOADER_START";

export const DASHBOARD_HR_SPEED_LOADER_END = "DASHBOARD_HR_SPEED_LOADER_END";
export const DASHBOARD_HR_RPM_LOADER_END = "DASHBOARD_HR_RPM_LOADER_END";
export const DASHBOARD_HR_FUEL_LOADER_END = "DASHBOARD_HR_FUEL_LOADER_END";

export const DASHBOARD_WK_SPEED_LOADER_END = "DASHBOARD_WK_SPEED_LOADER_END";
export const DASHBOARD_WK_RPM_LOADER_END = "DASHBOARD_WK_RPM_LOADER_END";
export const DASHBOARD_WK_FUEL_LOADER_END = "DASHBOARD_WK_FUEL_LOADER_END";
